// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: bitmex.proto

package bitmex_grpc_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_bitmex_proto protoreflect.FileDescriptor

const file_bitmex_proto_rawDesc = "" +
	"\n" +
	"\fbitmex.proto\x12\x06bitmex\x1a\vorder.proto\x1a\rutility.proto2\x90\x02\n" +
	"\rBitmexService\x124\n" +
	"\x05Login\x12\x14.bitmex.LoginRequest\x1a\x15.bitmex.LoginResponse\x12E\n" +
	"\tGetOrders\x12\x1c.bitmex.GetOrdersListRequest\x1a\x1a.bitmex.OrdersListResponse\x12@\n" +
	"\vCreateOrder\x12\x1a.bitmex.CreateOrderRequest\x1a\x15.bitmex.OrderResponse\x12@\n" +
	"\vCancelOrder\x12\x1a.bitmex.CancelOrderRequest\x1a\x15.bitmex.OrderResponse2\x85\x01\n" +
	"\x0eUtilityService\x121\n" +
	"\x04Ping\x12\x13.bitmex.PingRequest\x1a\x14.bitmex.PingResponse\x12@\n" +
	"\vSetLogLevel\x12\x17.bitmex.LogLevelRequest\x1a\x18.bitmex.LogLevelResponseB)Z'github.com/radiopapus/bitmex-grpc-protob\x06proto3"

var file_bitmex_proto_goTypes = []any{
	(*LoginRequest)(nil),         // 0: bitmex.LoginRequest
	(*GetOrdersListRequest)(nil), // 1: bitmex.GetOrdersListRequest
	(*CreateOrderRequest)(nil),   // 2: bitmex.CreateOrderRequest
	(*CancelOrderRequest)(nil),   // 3: bitmex.CancelOrderRequest
	(*PingRequest)(nil),          // 4: bitmex.PingRequest
	(*LogLevelRequest)(nil),      // 5: bitmex.LogLevelRequest
	(*LoginResponse)(nil),        // 6: bitmex.LoginResponse
	(*OrdersListResponse)(nil),   // 7: bitmex.OrdersListResponse
	(*OrderResponse)(nil),        // 8: bitmex.OrderResponse
	(*PingResponse)(nil),         // 9: bitmex.PingResponse
	(*LogLevelResponse)(nil),     // 10: bitmex.LogLevelResponse
}
var file_bitmex_proto_depIdxs = []int32{
	0,  // 0: bitmex.BitmexService.Login:input_type -> bitmex.LoginRequest
	1,  // 1: bitmex.BitmexService.GetOrders:input_type -> bitmex.GetOrdersListRequest
	2,  // 2: bitmex.BitmexService.CreateOrder:input_type -> bitmex.CreateOrderRequest
	3,  // 3: bitmex.BitmexService.CancelOrder:input_type -> bitmex.CancelOrderRequest
	4,  // 4: bitmex.UtilityService.Ping:input_type -> bitmex.PingRequest
	5,  // 5: bitmex.UtilityService.SetLogLevel:input_type -> bitmex.LogLevelRequest
	6,  // 6: bitmex.BitmexService.Login:output_type -> bitmex.LoginResponse
	7,  // 7: bitmex.BitmexService.GetOrders:output_type -> bitmex.OrdersListResponse
	8,  // 8: bitmex.BitmexService.CreateOrder:output_type -> bitmex.OrderResponse
	8,  // 9: bitmex.BitmexService.CancelOrder:output_type -> bitmex.OrderResponse
	9,  // 10: bitmex.UtilityService.Ping:output_type -> bitmex.PingResponse
	10, // 11: bitmex.UtilityService.SetLogLevel:output_type -> bitmex.LogLevelResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_bitmex_proto_init() }
func file_bitmex_proto_init() {
	if File_bitmex_proto != nil {
		return
	}
	file_order_proto_init()
	file_utility_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bitmex_proto_rawDesc), len(file_bitmex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_bitmex_proto_goTypes,
		DependencyIndexes: file_bitmex_proto_depIdxs,
	}.Build()
	File_bitmex_proto = out.File
	file_bitmex_proto_goTypes = nil
	file_bitmex_proto_depIdxs = nil
}
