// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: order.proto

package bitmex_grpc_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_LIMIT",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_LIMIT":       1,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

type CreateOrderRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OrdType OrderType              `protobuf:"varint,1,opt,name=OrdType,proto3,enum=bitmex.OrderType" json:"OrdType,omitempty"`
	// Like USDT
	Symbol        string  `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	ClOrdID       string  `protobuf:"bytes,3,opt,name=ClOrdID,proto3" json:"ClOrdID,omitempty"`
	Price         float64 `protobuf:"fixed64,4,opt,name=Price,proto3" json:"Price,omitempty"`
	OrderQty      int32   `protobuf:"varint,5,opt,name=OrderQty,proto3" json:"OrderQty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetOrdType() OrderType {
	if x != nil {
		return x.OrdType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateOrderRequest) GetClOrdID() string {
	if x != nil {
		return x.ClOrdID
	}
	return ""
}

func (x *CreateOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateOrderRequest) GetOrderQty() int32 {
	if x != nil {
		return x.OrderQty
	}
	return 0
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClOrdId       string                 `protobuf:"bytes,1,opt,name=ClOrdId,proto3" json:"ClOrdId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *CancelOrderRequest) GetClOrdId() string {
	if x != nil {
		return x.ClOrdId
	}
	return ""
}

type GetOrdersListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instrument symbol. Send a bare series (e.g. XBT) to get data for the nearest expiring contract in that series.
	// Can send a timeframe, e.g. XBT:quarterly. Timeframes are nearest, daily, weekly, monthly, quarterly,
	// biquarterly, and perpetual.
	// Symbols are case-insensitive.
	Symbol        string `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Start         int32  `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	Count         int32  `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersListRequest) Reset() {
	*x = GetOrdersListRequest{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersListRequest) ProtoMessage() {}

func (x *GetOrdersListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersListRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersListRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrdersListRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrdersListRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetOrdersListRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=Price,proto3" json:"Price,omitempty"`
	OrderType     string                 `protobuf:"bytes,2,opt,name=OrderType,proto3" json:"OrderType,omitempty"`
	ClOrdId       string                 `protobuf:"bytes,3,opt,name=ClOrdId,proto3" json:"ClOrdId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderResponse) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *OrderResponse) GetClOrdId() string {
	if x != nil {
		return x.ClOrdId
	}
	return ""
}

type OrdersListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderResponse       `protobuf:"bytes,1,rep,name=Orders,proto3" json:"Orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersListResponse) Reset() {
	*x = OrdersListResponse{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersListResponse) ProtoMessage() {}

func (x *OrdersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersListResponse.ProtoReflect.Descriptor instead.
func (*OrdersListResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrdersListResponse) GetOrders() []*OrderResponse {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x06bitmex\"\xa5\x01\n" +
	"\x12CreateOrderRequest\x12+\n" +
	"\aOrdType\x18\x01 \x01(\x0e2\x11.bitmex.OrderTypeR\aOrdType\x12\x16\n" +
	"\x06Symbol\x18\x02 \x01(\tR\x06Symbol\x12\x18\n" +
	"\aClOrdID\x18\x03 \x01(\tR\aClOrdID\x12\x14\n" +
	"\x05Price\x18\x04 \x01(\x01R\x05Price\x12\x1a\n" +
	"\bOrderQty\x18\x05 \x01(\x05R\bOrderQty\".\n" +
	"\x12CancelOrderRequest\x12\x18\n" +
	"\aClOrdId\x18\x01 \x01(\tR\aClOrdId\"Z\n" +
	"\x14GetOrdersListRequest\x12\x16\n" +
	"\x06Symbol\x18\x01 \x01(\tR\x06Symbol\x12\x14\n" +
	"\x05Start\x18\x02 \x01(\x05R\x05Start\x12\x14\n" +
	"\x05Count\x18\x03 \x01(\x05R\x05Count\"]\n" +
	"\rOrderResponse\x12\x14\n" +
	"\x05Price\x18\x01 \x01(\x01R\x05Price\x12\x1c\n" +
	"\tOrderType\x18\x02 \x01(\tR\tOrderType\x12\x18\n" +
	"\aClOrdId\x18\x03 \x01(\tR\aClOrdId\"C\n" +
	"\x12OrdersListResponse\x12-\n" +
	"\x06Orders\x18\x01 \x03(\v2\x15.bitmex.OrderResponseR\x06Orders*=\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x01B)Z'github.com/radiopapus/bitmex-grpc-protob\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_order_proto_goTypes = []any{
	(OrderType)(0),               // 0: bitmex.OrderType
	(*CreateOrderRequest)(nil),   // 1: bitmex.CreateOrderRequest
	(*CancelOrderRequest)(nil),   // 2: bitmex.CancelOrderRequest
	(*GetOrdersListRequest)(nil), // 3: bitmex.GetOrdersListRequest
	(*OrderResponse)(nil),        // 4: bitmex.OrderResponse
	(*OrdersListResponse)(nil),   // 5: bitmex.OrdersListResponse
}
var file_order_proto_depIdxs = []int32{
	0, // 0: bitmex.CreateOrderRequest.OrdType:type_name -> bitmex.OrderType
	4, // 1: bitmex.OrdersListResponse.Orders:type_name -> bitmex.OrderResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		EnumInfos:         file_order_proto_enumTypes,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
