// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: utility.proto

package bitmex_grpc_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_utility_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utility_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_utility_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=Reply,proto3" json:"Reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_utility_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utility_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_utility_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type LogLevelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уровень логирования (INFO, DEBUG, WARN, ERROR)
	Level         string `protobuf:"bytes,1,opt,name=Level,proto3" json:"Level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLevelRequest) Reset() {
	*x = LogLevelRequest{}
	mi := &file_utility_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLevelRequest) ProtoMessage() {}

func (x *LogLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utility_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLevelRequest.ProtoReflect.Descriptor instead.
func (*LogLevelRequest) Descriptor() ([]byte, []int) {
	return file_utility_proto_rawDescGZIP(), []int{2}
}

func (x *LogLevelRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type LogLevelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Результат
	Success       bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLevelResponse) Reset() {
	*x = LogLevelResponse{}
	mi := &file_utility_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLevelResponse) ProtoMessage() {}

func (x *LogLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utility_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLevelResponse.ProtoReflect.Descriptor instead.
func (*LogLevelResponse) Descriptor() ([]byte, []int) {
	return file_utility_proto_rawDescGZIP(), []int{3}
}

func (x *LogLevelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_utility_proto protoreflect.FileDescriptor

const file_utility_proto_rawDesc = "" +
	"\n" +
	"\rutility.proto\x12\x06bitmex\"\r\n" +
	"\vPingRequest\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05Reply\x18\x01 \x01(\tR\x05Reply\"'\n" +
	"\x0fLogLevelRequest\x12\x14\n" +
	"\x05Level\x18\x01 \x01(\tR\x05Level\",\n" +
	"\x10LogLevelResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccessB)Z'github.com/radiopapus/bitmex-grpc-protob\x06proto3"

var (
	file_utility_proto_rawDescOnce sync.Once
	file_utility_proto_rawDescData []byte
)

func file_utility_proto_rawDescGZIP() []byte {
	file_utility_proto_rawDescOnce.Do(func() {
		file_utility_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utility_proto_rawDesc), len(file_utility_proto_rawDesc)))
	})
	return file_utility_proto_rawDescData
}

var file_utility_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_utility_proto_goTypes = []any{
	(*PingRequest)(nil),      // 0: bitmex.PingRequest
	(*PingResponse)(nil),     // 1: bitmex.PingResponse
	(*LogLevelRequest)(nil),  // 2: bitmex.LogLevelRequest
	(*LogLevelResponse)(nil), // 3: bitmex.LogLevelResponse
}
var file_utility_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_utility_proto_init() }
func file_utility_proto_init() {
	if File_utility_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utility_proto_rawDesc), len(file_utility_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_utility_proto_goTypes,
		DependencyIndexes: file_utility_proto_depIdxs,
		MessageInfos:      file_utility_proto_msgTypes,
	}.Build()
	File_utility_proto = out.File
	file_utility_proto_goTypes = nil
	file_utility_proto_depIdxs = nil
}
